---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: false
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
- name: project_year
  type: datetime
  label: Year
  description: The year in which the project was completed.
  config:
    required: false
    date_format: YYYY
    time_format: 
    display_utc: false
    export_format: YYYY
  default: now
- name: published
  type: boolean
  label: Published
  default: false
  description: Is the page visible on the published site
pages:
- projects/eventscape-manila-x-echochannels-reinvent-the-rules.md
- projects/marks-logos-logotypes-2019-2020.md
- projects/redbox-asia-coffeetable-book.md
- projects/the-drop.md
